package com.adenki.smpp.event;

import com.adenki.smpp.Session;
import com.adenki.smpp.SessionState;

/**
 * Event generated by the receiver thread when a non-fatal exception is caught.
 * An application will receive this event type if the receiver thread catches an
 * exception which does not cause it to terminate. The exception which was
 * caught and the state the connection was in when it was caught are saved in
 * this event.
 * 
 * @version $Id$
 */
public class ReceiverExceptionEvent extends SMPPEvent {
    /**
     * The exception that was caught.
     */
    private Throwable exception;

    /**
     * The state the Connection was in when the exception was caught.
     */
    private SessionState connectionState;

    /**
     * Create a new ReceiverExceptionEvent.
     * 
     * @param source The source Connection of this event.
     * @param t The exception being reported.
     */
    public ReceiverExceptionEvent(Session source, Throwable t) {
        super(RECEIVER_EXCEPTION, source);
        this.exception = t;
    }

    /**
     * Create a new ReceiverExceptionEvent.
     * 
     * @param source The source Connection of this event.
     * @param t The exception being reported.
     * @param state The state the connection was in when the exception was
     * caught.
     */
    public ReceiverExceptionEvent(Session source, Throwable t, SessionState state) {
        super(RECEIVER_EXCEPTION, source);
        this.exception = t;
        this.connectionState = state;
    }

    /**
     * Get the exception which was caught.
     */
    public Throwable getException() {
        return exception;
    }

    /**
     * Get the state the connection was in when the exception was caught.
     * 
     * @return the integer value representing the state of the connection.
     * @see SessionState
     */
    public SessionState getState() {
        return connectionState;
    }
}

